apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-optimizer-frontend
  labels:
    app: flight-optimizer-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flight-optimizer-frontend
  template:
    metadata:
      labels:
        app: flight-optimizer-frontend
    spec:
      containers:
      - name: frontend
        image: hridayesh68/flight-optimizer-dsa-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: flight-optimizer-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
